flowchart TD

A[Email Notification: User recieve email to update info] --> B[Email Notification: User clicks reference link]
B --> C[Email Notification: Redirect to Registration form page]
C --> D[API: Load user existing info to allow user update info]
D --> E[Registration Form: Present User info]
E --> F[Registration Form: User edit their info and submit]
F --> G[Preview Page: Review User Data]
G --> H{Preview Page: User choose PDPA option}
H --> |Preview Page: Edit information| E
H --> |Preview Page: PDPA Accepted| I{Preview Page: User choose}
I --> |Preview Page: User Unchecked| G
I --> |Preview Page: Edit information| E
I --> |Preview Page: PDPA Accepted & Submit| J[Register Status Page: Display User Tracking code]
J --> K[Landing Page: Display Hero Video]
