-- Migration: Additive Admin Invitations & Admin Users Status (Job 1)
-- Date: 2025-01-27
-- Description: Ensure admin_invitations table and admin_users.status column match specifications
-- This migration is additive and idempotent - it will not break existing data

-- 1. Create admin_status enum if it doesn't exist
DO $$ BEGIN
    CREATE TYPE admin_status AS ENUM ('active', 'suspended');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Ensure admin_users.status column exists with proper type and constraints
ALTER TABLE admin_users 
ADD COLUMN IF NOT EXISTS status admin_status NOT NULL DEFAULT 'active';

-- 3. Ensure admin_invitations table exists with exact specifications
CREATE TABLE IF NOT EXISTS admin_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email CITEXT NOT NULL,
  roles TEXT[] NOT NULL DEFAULT '{}',
  token TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')) DEFAULT 'pending',
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID NOT NULL,
  accepted_at TIMESTAMPTZ,
  accepted_by UUID,
  correlation_id UUID NOT NULL DEFAULT gen_random_uuid()
);

-- 4. Create required indexes for admin_invitations
CREATE INDEX IF NOT EXISTS idx_admin_inv_email ON admin_invitations(email);
CREATE INDEX IF NOT EXISTS idx_admin_inv_expires ON admin_invitations(expires_at);
CREATE INDEX IF NOT EXISTS idx_admin_inv_status ON admin_invitations(status);

-- 5. Create partial unique constraint to prevent duplicate pending invitations for same email
CREATE UNIQUE INDEX IF NOT EXISTS admin_inv_unique_pending 
ON admin_invitations (email) WHERE status = 'pending';

-- 6. Ensure admin_users has proper email unique constraint
CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_users_email_unique 
ON admin_users(email);

-- 7. Create indexes for admin_users status and role for RBAC filtering
CREATE INDEX IF NOT EXISTS idx_admin_users_status ON admin_users(status);
CREATE INDEX IF NOT EXISTS idx_admin_users_role ON admin_users(role);
CREATE INDEX IF NOT EXISTS idx_admin_users_role_status ON admin_users(role, status);

-- 8. Add comments for documentation
COMMENT ON TABLE admin_invitations IS 'Admin invitation system for onboarding new administrators';
COMMENT ON COLUMN admin_invitations.email IS 'Email address of the invited admin (case-insensitive)';
COMMENT ON COLUMN admin_invitations.roles IS 'Array of role slugs assigned to the invitation';
COMMENT ON COLUMN admin_invitations.token IS 'Cryptographically secure token for invitation acceptance';
COMMENT ON COLUMN admin_invitations.status IS 'Current status of the invitation (pending, accepted, expired, revoked)';
COMMENT ON COLUMN admin_invitations.expires_at IS 'Expiration timestamp (48 hours from creation)';
COMMENT ON COLUMN admin_invitations.created_by IS 'UUID of the admin who created the invitation';
COMMENT ON COLUMN admin_invitations.accepted_by IS 'UUID of the admin who accepted the invitation';
COMMENT ON COLUMN admin_invitations.correlation_id IS 'Unique correlation ID for tracking invitation lifecycle';

COMMENT ON COLUMN admin_users.status IS 'Admin user status (active, suspended) for RBAC filtering';
COMMENT ON INDEX admin_inv_unique_pending IS 'Prevents duplicate pending invitations for the same email address';

-- 9. Create function to generate secure invitation tokens (if not exists)
CREATE OR REPLACE FUNCTION generate_admin_invitation_token()
RETURNS TEXT AS $$
BEGIN
  -- Generate a cryptographically secure random token
  -- Using 32 bytes of random data encoded as base64
  RETURN encode(gen_random_bytes(32), 'base64');
END;
$$ LANGUAGE plpgsql;

-- 10. Create function to clean up expired invitations (if not exists)
CREATE OR REPLACE FUNCTION cleanup_expired_admin_invitations()
RETURNS void AS $$
BEGIN
  UPDATE admin_invitations 
  SET status = 'expired'
  WHERE status = 'pending' 
  AND expires_at < now();
END;
$$ LANGUAGE plpgsql;

-- 11. Add comments for functions
COMMENT ON FUNCTION generate_admin_invitation_token() IS 'Generates a cryptographically secure token for admin invitations';
COMMENT ON FUNCTION cleanup_expired_admin_invitations() IS 'Marks expired invitations as expired (run periodically)';

-- 12. Create RLS policies for admin_invitations (if RLS is enabled)
DO $$
BEGIN
  -- Only create policies if RLS is enabled
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'admin_invitations' 
    AND table_schema = 'public'
  ) THEN
    -- Enable RLS if not already enabled
    ALTER TABLE admin_invitations ENABLE ROW LEVEL SECURITY;
    
    -- Drop existing policies if they exist
    DROP POLICY IF EXISTS "Super admins can manage admin invitations" ON admin_invitations;
    DROP POLICY IF EXISTS "Service role can manage admin invitations" ON admin_invitations;
    DROP POLICY IF EXISTS "Public can accept invitations by token" ON admin_invitations;
    
    -- Super admins can manage all invitations
    CREATE POLICY "Super admins can manage admin invitations" ON admin_invitations
      FOR ALL USING (
        EXISTS (
          SELECT 1 FROM admin_users au
          WHERE au.id = auth.uid()
          AND au.role = 'super_admin'
          AND au.is_active = true
          AND au.status = 'active'
        )
      );
    
    -- Service role can manage all invitations (for API operations)
    CREATE POLICY "Service role can manage admin invitations" ON admin_invitations
      FOR ALL USING (auth.role() = 'service_role');
    
    -- Public can update invitations by token (for acceptance flow)
    CREATE POLICY "Public can accept invitations by token" ON admin_invitations
      FOR UPDATE USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- 13. Create a trigger to automatically update updated_at timestamp for admin_invitations
CREATE OR REPLACE FUNCTION update_admin_invitations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Only create trigger if updated_at column exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'admin_invitations' 
    AND column_name = 'updated_at'
    AND table_schema = 'public'
  ) THEN
    DROP TRIGGER IF EXISTS trigger_admin_invitations_updated_at ON admin_invitations;
    CREATE TRIGGER trigger_admin_invitations_updated_at
      BEFORE UPDATE ON admin_invitations
      FOR EACH ROW
      EXECUTE FUNCTION update_admin_invitations_updated_at();
  END IF;
END $$;
