-- Migration: Email Outbox Table for Test Provider
-- Date: 2025-01-27
-- Description: Create email_outbox table for TestEmailProvider to store emails for E2E testing

-- Create email_outbox table for storing test emails
CREATE TABLE IF NOT EXISTS email_outbox (
  id TEXT PRIMARY KEY,
  to_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  text_content TEXT NOT NULL,
  template TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'failed', 'pending')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  error_message TEXT
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_email_outbox_template ON email_outbox(template);
CREATE INDEX IF NOT EXISTS idx_email_outbox_to_email ON email_outbox(to_email);
CREATE INDEX IF NOT EXISTS idx_email_outbox_created_at ON email_outbox(created_at);
CREATE INDEX IF NOT EXISTS idx_email_outbox_status ON email_outbox(status);

-- Create composite index for common queries
CREATE INDEX IF NOT EXISTS idx_email_outbox_template_to_email ON email_outbox(template, to_email);

-- Add comments for documentation
COMMENT ON TABLE email_outbox IS 'Email outbox for storing test emails sent by TestEmailProvider';
COMMENT ON COLUMN email_outbox.id IS 'Unique message ID generated by the email provider';
COMMENT ON COLUMN email_outbox.to_email IS 'Recipient email address';
COMMENT ON COLUMN email_outbox.subject IS 'Email subject line';
COMMENT ON COLUMN email_outbox.html_content IS 'HTML content of the email';
COMMENT ON COLUMN email_outbox.text_content IS 'Plain text content of the email';
COMMENT ON COLUMN email_outbox.template IS 'Template identifier (e.g., admin.invitation)';
COMMENT ON COLUMN email_outbox.payload IS 'JSON payload with template variables';
COMMENT ON COLUMN email_outbox.status IS 'Email status (sent, failed, pending)';
COMMENT ON COLUMN email_outbox.created_at IS 'Timestamp when email was created';
COMMENT ON COLUMN email_outbox.sent_at IS 'Timestamp when email was sent (if different from created_at)';
COMMENT ON COLUMN email_outbox.error_message IS 'Error message if email sending failed';

-- Create RLS policies for email_outbox (if RLS is enabled)
DO $$
BEGIN
  -- Only create policies if RLS is enabled
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'email_outbox' 
    AND table_schema = 'public'
  ) THEN
    -- Enable RLS if not already enabled
    ALTER TABLE email_outbox ENABLE ROW LEVEL SECURITY;
    
    -- Drop existing policies if they exist
    DROP POLICY IF EXISTS "Super admins can view email outbox" ON email_outbox;
    DROP POLICY IF EXISTS "Service role can manage email outbox" ON email_outbox;
    
    -- Super admins can view email outbox
    CREATE POLICY "Super admins can view email outbox" ON email_outbox
      FOR SELECT USING (
        EXISTS (
          SELECT 1 FROM admin_users au
          WHERE au.id = auth.uid()
          AND au.role = 'super_admin'
          AND au.is_active = true
          AND au.status = 'active'
        )
      );
    
    -- Service role can manage all email outbox entries (for API operations)
    CREATE POLICY "Service role can manage email outbox" ON email_outbox
      FOR ALL USING (auth.role() = 'service_role');
  END IF;
END $$;

-- Create function to clean up old email outbox entries
CREATE OR REPLACE FUNCTION cleanup_old_email_outbox(older_than_days INTEGER DEFAULT 7)
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM email_outbox 
  WHERE created_at < now() - INTERVAL '1 day' * older_than_days;
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_old_email_outbox(INTEGER) IS 'Cleans up email outbox entries older than specified days (default 7)';

-- Create function to get email outbox statistics
CREATE OR REPLACE FUNCTION get_email_outbox_stats()
RETURNS TABLE(
  total_emails BIGINT,
  sent_emails BIGINT,
  failed_emails BIGINT,
  pending_emails BIGINT,
  templates_used TEXT[],
  recent_activity TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::BIGINT as total_emails,
    COUNT(*) FILTER (WHERE status = 'sent')::BIGINT as sent_emails,
    COUNT(*) FILTER (WHERE status = 'failed')::BIGINT as failed_emails,
    COUNT(*) FILTER (WHERE status = 'pending')::BIGINT as pending_emails,
    ARRAY_AGG(DISTINCT template) as templates_used,
    MAX(created_at) as recent_activity
  FROM email_outbox;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_email_outbox_stats() IS 'Returns statistics about email outbox usage';
