name: CI Health Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  health_check:
    name: System Health Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # Use your existing .e2e-env configuration
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # Consistent with your system - PORT 8080
      NEXT_PUBLIC_SITE_URL: http://localhost:8080
      E2E_BASE_URL: http://localhost:8080
      # Core service flags
      FEATURES_ADMIN_MANAGEMENT: "true"
      E2E_TESTS: "true"
      E2E_TEST_MODE: "true"
      TEST_HELPERS_ENABLED: "1"
      # Security - use the actual CRON_SECRET from .e2e-env
      CRON_SECRET: "9318b95a82c5f8fcd236d8abe79f4ce8"
      SUPABASE_ENV: "staging"
      # Email configuration - use actual values from .e2e-env
      EMAIL_MODE: "CAPPED"
      DISPATCH_DRY_RUN: "false"
      E2E_DB_TARGET: "staging"
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      
      - name: Start application server
        run: |
          nohup npm run dev -- --port=8080 &
          sleep 15
          
      - name: Run health validation tests
        run: |
          npx playwright test tests/e2e/ci-health-check.spec.ts \
            --config=playwright.ci-health.config.ts \
            --reporter=line \
            --timeout=30000
