name: DB — Migrate to Staging

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

concurrency:
  group: db-staging-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write

jobs:
  detect_changes:
    name: detect_changes
    runs-on: ubuntu-latest
    outputs:
      db_changed: ${{ steps.filter.outputs.db }}
      db_files: ${{ steps.filter.outputs.db_files }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            db:
              - 'migrations/**/*.sql'
              - '.github/workflows/db-migrate-staging.yml'

  test_on_shadow:
    name: test_on_shadow
    needs: detect_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fast-pass when no DB changes
        if: needs.detect_changes.outputs.db_changed != 'true'
        run: echo "No DB changes; shadow test skipped (pass)."

      - name: Setup Supabase CLI
        if: needs.detect_changes.outputs.db_changed == 'true'
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install PostgreSQL client
        if: needs.detect_changes.outputs.db_changed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # ⬇️ ดึง snapshot จาก STAGING แล้วประกอบชุด migrations สำหรับ shadow
      - name: Build migration set for shadow (remote base + local)
        if: needs.detect_changes.outputs.db_changed == 'true'
        env:
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
        run: |
          set -euo pipefail
          rm -rf supabase/migrations
          mkdir -p supabase/migrations

          # 1) ดึง schema ปัจจุบันของ STAGING → 000_remote_base.sql
          pg_dump "$STAGING_DB_URL" \
            --schema-only --no-owner --no-privileges \
            --exclude-schema=pg_* --exclude-schema=information_schema \
            > supabase/migrations/000_remote_base.sql

          # 2) เติมไฟล์ migrations ใน repo ต่อท้าย
          cp -a migrations/. supabase/migrations/
          ls -la supabase/migrations

      - name: Start local Supabase (shadow) + apply
        if: needs.detect_changes.outputs.db_changed == 'true'
        run: |
          set -euo pipefail
          supabase start
          # reset จะอ่านไฟล์ใน supabase/migrations ตามลำดับ
          printf 'y\n' | supabase db reset

      - name: Report required context (ruleset-compat)
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const state = process.env.JOB_STATUS === 'success' ? 'success' : 'failure'
            const sha = context.payload.pull_request.head.sha
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner, repo: context.repo.repo, sha,
              state, context: 'DB — Migrate to Staging / test_on_shadow (pull_request)',
              description: `Run ${context.runId}`,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

  push_to_staging:
    name: push_to_staging
    needs: [detect_changes, test_on_shadow]
    if: needs.detect_changes.outputs.db_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply changed migrations to STAGING (psql)
        env:
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
          CHANGED: ${{ needs.detect_changes.outputs.db_files }}
        run: |
          set -euo pipefail
          echo "Changed migration files:"
          echo "$CHANGED"

          # กันกรณี output ว่าง
          if [ -z "$CHANGED" ]; then
            echo "No changed .sql files detected."
            exit 0
          fi

          # รันตามลำดับชื่อไฟล์ (prefix timestamp)
          for f in $(echo "$CHANGED" | tr ' ' '\n' | sort); do
            echo "==> Applying $f"
            psql "$STAGING_DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done

