name: DB — Migrate to Staging

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/seed.sql'
      - '.github/workflows/db-migrate-staging.yml'
  push:
    branches: [main, develop]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/seed.sql'

concurrency:
  group: db-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_on_shadow:
    name: Test migrations on Shadow DB
    runs-on: ubuntu-latest
    services:
      postgres:
        # ใช้ Postgres ของ Supabase เพื่อให้มี extensions พร้อม
        image: supabase/postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - uses: supabase/setup-cli@v1
        with:
          version: latest      # <-- สำคัญ: ใช้ CLI ล่าสุดให้รองรับ key ใหม่ ๆ ใน config.toml
      - name: Apply migrations to shadow
        env:
          SHADOW_DB_URL: postgresql://postgres:postgres@localhost:5432/postgres
        shell: bash
        run: |
          set -euo pipefail
          # บางเวอร์ชันมีคำถามยืนยัน ใช้ yes ป้อนให้
          if yes | supabase db reset --db-url "$SHADOW_DB_URL"; then
            echo "Reset & apply migrations to shadow: OK"
          fi
          if [ -f supabase/seed.sql ]; then psql "$SHADOW_DB_URL" -f supabase/seed.sql; fi

  push_to_staging:
    name: Push migrations to Staging
    needs: [test_on_shadow]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Push → Staging (link or DB URL fallback)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SB_STAGING_REF: ${{ secrets.SB_STAGING_REF }}
          # (ถ้าต้องการ) STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Trying: supabase link → supabase db push"
          if supabase link --project-ref "$SB_STAGING_REF"; then
            supabase db push
            exit 0
          fi
          echo "Link failed. Checking STAGING_DB_URL fallback..."
          if [[ -n "${STAGING_DB_URL:-}" ]]; then
            supabase db push --db-url "$STAGING_DB_URL"
            exit 0
          fi
          echo "No STAGING_DB_URL provided and link failed." >&2
          exit 1

