name: DB — Migrate to Staging

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

concurrency:
  group: db-staging-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write

jobs:
  detect_changes:
    name: detect_changes
    runs-on: ubuntu-latest
    outputs:
      db_changed: ${{ steps.filter.outputs.db }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            db:
              - 'migrations/**'
              - 'supabase/migrations/**'
              - '.github/workflows/db-migrate-staging.yml'

  test_on_shadow:
    name: test_on_shadow
    needs: detect_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fast-pass when no DB changes
        if: needs.detect_changes.outputs.db_changed != 'true'
        run: echo "No DB changes; shadow test skipped (pass)."

      - name: Setup Supabase CLI
        if: needs.detect_changes.outputs.db_changed == 'true'
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # ⬇️ สำคัญ: ดึง snapshot จาก STAGING แล้วทำไฟล์ 000_remote_base.sql
      - name: Build migration set (remote base + local)
        if: needs.detect_changes.outputs.db_changed == 'true'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SB_STAGING_REF: ${{ secrets.SB_STAGING_REF }}
          STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
        run: |
          set -euo pipefail
          rm -rf supabase/migrations
          mkdir -p supabase/migrations
          # 1) ดึง snapshot schema จาก Staging
          supabase db pull --db-url "$STAGING_DB_URL"
          SNAP=$(ls -1t supabase/migrations/*_snapshot.sql | head -1)
          mv "$SNAP" supabase/migrations/000_remote_base.sql
          # 2) เติมไฟล์ migrations ใน repo ต่อท้าย
          cp -a migrations/. supabase/migrations/
          ls -la supabase/migrations

      - name: Start local Supabase (shadow) + apply
        if: needs.detect_changes.outputs.db_changed == 'true'
        env:
          SHADOW_DB_URL: postgresql://postgres:postgres@localhost:54322/postgres
        run: |
          set -euo pipefail
          supabase start
          # reset จะอ่านตามลำดับไฟล์ใน supabase/migrations
          printf 'y\n' | supabase db reset --db-url "$SHADOW_DB_URL"

      - name: Report required context (ruleset-compat)
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const state = process.env.JOB_STATUS === 'success' ? 'success' : 'failure'
            const sha = context.payload.pull_request.head.sha
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner, repo: context.repo.repo, sha,
              state, context: 'DB — Migrate to Staging / test_on_shadow (pull_request)',
              description: `Run ${context.runId}`,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

  push_to_staging:
    name: push_to_staging
    needs: [detect_changes, test_on_shadow]
    if: needs.detect_changes.outputs.db_changed == 'true'
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SB_STAGING_REF: ${{ secrets.SB_STAGING_REF }}
      STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # ซิงก์โครงสร้างจาก Staging มาก่อน เพื่อให้ history ตรงกัน
      - name: Sync local with remote history
        run: |
          set -euo pipefail
          rm -rf supabase/migrations
          mkdir -p supabase/migrations
          supabase db pull --db-url "$STAGING_DB_URL"
          cp -a migrations/. supabase/migrations/
          ls -la supabase/migrations

      - name: Push migrations → Staging
        run: |
          set -euo pipefail
          supabase db push --db-url "$STAGING_DB_URL"

