name: DB — Promote Staging → Prod

on:
  push:
    branches: [ main ]            # รันจริงหลัง merge
  pull_request:                    # ให้ PR ได้สถานะ required (no-op)
    types: [opened, synchronize, reopened]
  workflow_dispatch:               # manual promote/hotfix
    inputs:
      skip_shadow:
        description: "Skip shadow test (not recommended)"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

concurrency:
  group: db-prod-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  statuses: write

# ---------- PR ONLY: โพสต์สถานะ context ให้ PR ไม่ค้าง Expected ----------
jobs:
  report_required_status_for_pr:
    name: report_required_status_for_pr
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Report required context for PR (no-op)
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'success',
              context: 'DB — Promote Staging → Prod / push_to_prod (push)',
              description: 'PR no-op status to satisfy ruleset',
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });

# ---------- PRODUCTION STAGE: ทำงานจริงบน push → main หรือ manual ----------
  detect_changes:
    name: detect_changes
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      db_changed: ${{ steps.filter.outputs.db }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            db:
              - 'supabase/migrations/**'
              - '.github/workflows/db-promote-prod.yml'

  test_on_shadow:
    name: test_on_shadow
    needs: detect_changes
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
        needs.detect_changes.outputs.db_changed == 'true' &&
        !(github.event_name == 'workflow_dispatch' && github.event.inputs.skip_shadow == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Start local Supabase (shadow)
        run: |
          supabase start
          supabase status
      - name: Apply migrations to shadow
        env:
          SHADOW_DB_URL: postgresql://postgres:postgres@localhost:54322/postgres
        shell: bash
        run: |
          set -euo pipefail
          printf 'y\n' | supabase db reset --db-url "$SHADOW_DB_URL"

  noop_when_not_db:
    name: No DB changes → fast-pass
    needs: detect_changes
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
        needs.detect_changes.outputs.db_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes under supabase/migrations; DB promotion skipped."

  push_to_prod:
    name: push_to_prod
    needs: [detect_changes, test_on_shadow]
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
        needs.detect_changes.outputs.db_changed == 'true'
    runs-on: ubuntu-latest
    environment:
      name: production            # ใช้ Environment approval ที่นี่
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase (prod)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase link --project-ref ${{ secrets.SB_PROD_REF }}

      - name: Backup current prod schema (pre-push)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          mkdir -p db-backups
          supabase db pull --project-ref ${{ secrets.SB_PROD_REF }}
          cp -f supabase/.temp/schema.sql db-backups/prod-before.sql || true

      - name: Push migrations → Prod (requires environment approval)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push

      - name: Upload backup artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prod-schema-backup
          path: db-backups/
          retention-days: 14

  # ---- Vercel Prod Deploy: กรณีมี DB change → รอหลัง push_to_prod เสมอ ----
  vercel_production_after_db:
    name: vercel_production
    needs: [detect_changes, push_to_prod]
    if: github.event_name == 'push' && needs.detect_changes.outputs.db_changed == 'true'
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Vercel pull (prod)
        run: npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
      - name: Vercel build (prod)
        run: npx vercel build --prod --token "$VERCEL_TOKEN"
      - name: Vercel deploy (prod)
        run: npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"

  # ---- Vercel Prod Deploy: กรณีไม่มี DB change → deploy ทันทีหลังตรวจ diff ----
  vercel_production_no_db:
    name: vercel_production (no-db-change)
    needs: [detect_changes]
    if: github.event_name == 'push' && needs.detect_changes.outputs.db_changed != 'true'
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Vercel pull (prod)
        run: npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
      - name: Vercel build (prod)
        run: npx vercel build --prod --token "$VERCEL_TOKEN"
      - name: Vercel deploy (prod)
        run: npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"

