name: E2E Audit Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit_diag:
    name: audit_diag
    runs-on: ubuntu-latest
    # ถ้าเป็น PR จาก fork และไม่มี secrets ให้ skip เพื่อไม่ล้มผิดเหตุ
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run @audit diag tests (with fallback)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ENV: 'staging'
        run: |
          set -e
          if [ -f "tests/e2e/audit-diag.e2e.spec.ts" ]; then
            npx playwright test tests/e2e/audit-diag.e2e.spec.ts --reporter=line
          else
            npx playwright test --grep="@audit @diag" --reporter=line
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-audit
          path: playwright-report/
          retention-days: 14

