name: E2E Dispatch Emails Tests

on:
  pull_request:
    paths:
      - ".github/workflows/e2e-dispatch-emails.yml"
      - "playwright.config.ts"
      - "tests/**"
      - "app/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "npm-shrinkwrap.json"

jobs:
  dispatch_emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install deps
        run: npm ci

      # ✅ สร้าง .env.ci จาก GitHub Secrets (อย่าคอมมิตไฟล์ env)
      - name: Create .env.ci from secrets
        run: |
          echo "CRON_SECRET=${{ secrets.CRON_SECRET }}" >> .env.ci
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.ci
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.ci
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.ci
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.ci
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env.ci
          # คอนฟิกโหมดทดสอบ: ไม่ส่งอีเมลจริง
          echo "SUPABASE_ENV=staging" >> .env.ci
          echo "DISPATCH_DRY_RUN=true" >> .env.ci
          echo "EMAIL_MODE=DRY_RUN" >> .env.ci
          echo "EMAIL_FROM=noreply@local.test" >> .env.ci
          echo "EMAIL_ALLOWLIST=test@example.com" >> .env.ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E (dispatch emails)
        env:
          CI: "true"
        run: npx playwright test tests/e2e/dispatch-emails.e2e.spec.ts --reporter=line

