name: E2E Audit Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1) ตรวจว่ามีไฟล์ที่เกี่ยวกับ audit เปลี่ยนจริงไหม เพื่อประหยัดเวลา/เครดิต
  changes:
    runs-on: ubuntu-latest
    outputs:
      audit: ${{ steps.filter.outputs.audit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect relevant changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            audit:
              - 'tests/e2e/**'
              - 'playwright.config.ts'
              - 'app/lib/audit/**'
              - 'app/admin/audit/**'
              - 'app/lib/events/**'
              - 'app/api/**'
              - '.github/workflows/e2e-audit.yml'

  # 2) รันชุดตรวจสุขภาพอย่างรวดเร็ว (@audit @diag)
  audit_diag:
    needs: changes
    runs-on: ubuntu-latest
    # ไม่รันกับ PR จาก fork (เพื่อป้องกัน secrets รั่ว) และรันเฉพาะเมื่อมีไฟล์ที่เกี่ยวข้องเปลี่ยน
    if: >
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository) &&
      needs.changes.outputs.audit == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ใช้สคริปต์โปรเจกต์ของคุณโดยตรง (ไม่ใช้ --grep เพื่อเลี่ยงปัญหา No tests found)
      - name: Run audit diag
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PLAYWRIGHT_TEST: '1'
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run test:audit

      - name: Upload Playwright report (diag)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-diag
          path: playwright-report/
          retention-days: 30

      - name: Upload test artifacts (diag)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-diag
          path: test-artifacts/
          retention-days: 30

  # 3) ถ้า diag ผ่าน ค่อยรันชุดเต็มของ audit
  audit_full:
    needs: [changes, audit_diag]
    runs-on: ubuntu-latest
    if: >
      needs.changes.outputs.audit == 'true' &&
      needs.audit_diag.result == 'success' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # รันไฟล์ audit ทั้งหมดแบบชี้ไฟล์ โดยไม่พึ่ง --grep (กันเคสหาเทสต์ไม่เจอ)
      - name: Run full audit suite
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PLAYWRIGHT_TEST: '1'
          NEXT_TELEMETRY_DISABLED: '1'
        run: |
          npx playwright test \
            tests/e2e/audit-diag.e2e.spec.ts \
            tests/e2e/audit-login.e2e.spec.ts \
            tests/e2e/audit.e2e.spec.ts \
            tests/e2e/audit-dashboard.e2e.spec.ts \
            --reporter=line

      - name: Upload Playwright report (full)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-full
          path: playwright-report/
          retention-days: 30

      - name: Upload test artifacts (full)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-full
          path: test-artifacts/
          retention-days: 30

