name: Lint, ESLint, Check format, Prettier

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci

      - name: ESLint (strict)
        run: npm run lint:strict

      - name: Prettier check (non-blocking on PR)
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          npx prettier -c "{src,app,apps,packages,lib,components,scripts,server,client}/**/*.{ts,tsx,js,jsx,json,css,md}" \
            || echo "::warning::Prettier found issues. Run 'npm run format'."

      - name: Prettier check (blocking on push)
        if: github.event_name != 'pull_request'
        run: |
          npx prettier -c "{src,app,apps,packages,lib,components,scripts,server,client}/**/*.{ts,tsx,js,jsx,json,css,md}"

